export const zkFloors = [
  {
    id: 'floor-01',
    number: 'ЭТАЖ 01',
    title: 'Фундамент (LEGO)',
    description:
      'Конечные Поля. Здесь мы лепим кирпичи, которые нельзя разделить. Основа всей стройки.',
    status: 'ready',
    accent: 'primary',
    route: 'zk/floor-01',
    source: 'no_division_cult.html',
    tags: ['finite-field', 'basics'],
  },
  {
    id: 'floor-02',
    number: 'ЭТАЖ 02',
    title: 'Электрика и Трубы',
    description:
      'Арифметические Схемы. Прокладываем проводку (Wires) и ставим вентили (Gates). Логика здания.',
    status: 'ready',
    accent: 'primary',
    route: 'zk/floor-02',
    source: 'zk_pinball_madness.html',
    tags: ['circuits', 'gates'],
  },
  {
    id: 'floor-03',
    number: 'ЭТАЖ 03',
    title: 'Чертеж Крыши',
    description:
      'Интерполяция. Как накрыть кучу торчащих балок одной идеальной волнистой крышей (Полином).',
    status: 'ready',
    accent: 'primary',
    route: 'zk/floor-03',
    source: 'polynomial_factory.html',
    tags: ['interpolation', 'polynomials'],
  },
  {
    id: 'floor-04',
    number: 'ЭТАЖ 04',
    title: 'Журнал Прораба',
    description: 'Trace -> Poly. Превращаем скучные отчеты о работе в математическую формулу.',
    status: 'ready',
    accent: 'primary',
    route: 'zk/floor-04',
    source: 'trace_to_polynomial.html',
    tags: ['trace', 'polynomials'],
  },
  {
    id: 'floor-05',
    number: 'ЭТАЖ 05',
    title: 'Злой Вахтер',
    description:
      'Меркл-дерево. Вахтер (Root) следит, чтобы никто не украл кирпичи со стройки.',
    status: 'ready',
    accent: 'primary',
    route: 'zk/floor-05',
    source: 'merkle_dogs.html',
    tags: ['merkle', 'commitments'],
  },
  {
    id: 'floor-06',
    number: 'ЭТАЖ 06',
    title: 'Чемодан',
    description: 'ZK Декомпрессия. Как упаковать целый дом в один чемодан для отправки заказчику.',
    status: 'ready',
    accent: 'primary',
    route: 'zk/floor-06',
    source: 'zk_decompression.html',
    tags: ['compression', 'zk'],
  },
  {
    id: 'floor-07',
    number: 'ЭТАЖ 07',
    title: 'Краш-Тест (FRI)',
    description: 'Сворачиваем чертежи в оригами. Проверяем прочность конструкции случайными ударами.',
    status: 'active',
    accent: 'secondary',
    route: 'zk/floor-07',
    source: 'zk_proving_matrix.html',
    tags: ['fri', 'testing'],
  },
  {
    id: 'floor-08',
    number: 'ПЕНТХАУС',
    title: 'Цитадель Бутерина',
    description:
      'Аттестация. Финальная проверка. Если прораб не врал, мы получаем ключи от города (Ethereum).',
    status: 'soon',
    accent: 'primary',
    route: 'zk/floor-08',
    source: 'attestation_citadel.html',
    tags: ['attestation', 'ethereum'],
  },
];

export const zkLanding = {
  id: 'zk',
  title: 'FORTRESS BUTERINKA',
  subtitle: 'Строим Небоскреб Истины (ZK). От фундамента до аттестации.',
  route: 'zk',
};
